/**
 * Do not edit directly, this file was auto-generated.
 */

var _styleDictionary = {
  color: {
    base: {
      white: {
        key: "{color.base.white}",
        value: "#ffffff",
        filePath: "design-tokens/core/color.json",
        isSource: true,
        original: {
          value: "#ffffff",
          key: "{color.base.white}",
        },
        name: "ColorBaseWhite",
        attributes: {
          category: "color",
          type: "base",
          item: "white",
        },
        path: ["color", "base", "white"],
      },
      black: {
        key: "{color.base.black}",
        value: "#000000",
        filePath: "design-tokens/core/color.json",
        isSource: true,
        original: {
          value: "#000000",
          key: "{color.base.black}",
        },
        name: "ColorBaseBlack",
        attributes: {
          category: "color",
          type: "base",
          item: "black",
        },
        path: ["color", "base", "black"],
      },
      transparent: {
        key: "{color.base.transparent}",
        value: "transparent",
        filePath: "design-tokens/core/color.json",
        isSource: true,
        original: {
          value: "transparent",
          key: "{color.base.transparent}",
        },
        name: "ColorBaseTransparent",
        attributes: {
          category: "color",
          type: "base",
          item: "transparent",
        },
        path: ["color", "base", "transparent"],
      },
    },
    gray: {
      50: {
        key: "{color.gray.50}",
        value: "#f9fafb",
        filePath: "design-tokens/core/color.json",
        isSource: true,
        original: {
          value: "#f9fafb",
          key: "{color.gray.50}",
        },
        name: "ColorGray50",
        attributes: {
          category: "color",
          type: "gray",
          item: "50",
        },
        path: ["color", "gray", "50"],
      },
      100: {
        key: "{color.gray.100}",
        value: "#f3f4f6",
        filePath: "design-tokens/core/color.json",
        isSource: true,
        original: {
          value: "#f3f4f6",
          key: "{color.gray.100}",
        },
        name: "ColorGray100",
        attributes: {
          category: "color",
          type: "gray",
          item: "100",
        },
        path: ["color", "gray", "100"],
      },
      200: {
        key: "{color.gray.200}",
        value: "#e5e7eb",
        filePath: "design-tokens/core/color.json",
        isSource: true,
        original: {
          value: "#e5e7eb",
          key: "{color.gray.200}",
        },
        name: "ColorGray200",
        attributes: {
          category: "color",
          type: "gray",
          item: "200",
        },
        path: ["color", "gray", "200"],
      },
      300: {
        key: "{color.gray.300}",
        value: "#d1d5db",
        filePath: "design-tokens/core/color.json",
        isSource: true,
        original: {
          value: "#d1d5db",
          key: "{color.gray.300}",
        },
        name: "ColorGray300",
        attributes: {
          category: "color",
          type: "gray",
          item: "300",
        },
        path: ["color", "gray", "300"],
      },
      400: {
        key: "{color.gray.400}",
        value: "#9ca3af",
        filePath: "design-tokens/core/color.json",
        isSource: true,
        original: {
          value: "#9ca3af",
          key: "{color.gray.400}",
        },
        name: "ColorGray400",
        attributes: {
          category: "color",
          type: "gray",
          item: "400",
        },
        path: ["color", "gray", "400"],
      },
      500: {
        key: "{color.gray.500}",
        value: "#6b7280",
        filePath: "design-tokens/core/color.json",
        isSource: true,
        original: {
          value: "#6b7280",
          key: "{color.gray.500}",
        },
        name: "ColorGray500",
        attributes: {
          category: "color",
          type: "gray",
          item: "500",
        },
        path: ["color", "gray", "500"],
      },
      600: {
        key: "{color.gray.600}",
        value: "#4b5563",
        filePath: "design-tokens/core/color.json",
        isSource: true,
        original: {
          value: "#4b5563",
          key: "{color.gray.600}",
        },
        name: "ColorGray600",
        attributes: {
          category: "color",
          type: "gray",
          item: "600",
        },
        path: ["color", "gray", "600"],
      },
      700: {
        key: "{color.gray.700}",
        value: "#374151",
        filePath: "design-tokens/core/color.json",
        isSource: true,
        original: {
          value: "#374151",
          key: "{color.gray.700}",
        },
        name: "ColorGray700",
        attributes: {
          category: "color",
          type: "gray",
          item: "700",
        },
        path: ["color", "gray", "700"],
      },
      800: {
        key: "{color.gray.800}",
        value: "#1f2937",
        filePath: "design-tokens/core/color.json",
        isSource: true,
        original: {
          value: "#1f2937",
          key: "{color.gray.800}",
        },
        name: "ColorGray800",
        attributes: {
          category: "color",
          type: "gray",
          item: "800",
        },
        path: ["color", "gray", "800"],
      },
      900: {
        key: "{color.gray.900}",
        value: "#111827",
        filePath: "design-tokens/core/color.json",
        isSource: true,
        original: {
          value: "#111827",
          key: "{color.gray.900}",
        },
        name: "ColorGray900",
        attributes: {
          category: "color",
          type: "gray",
          item: "900",
        },
        path: ["color", "gray", "900"],
      },
    },
  },
  typography: {
    font: {
      family: {
        primary: {
          key: "{typography.font.family.primary}",
          value: "Mulish, sans-serif",
          filePath: "design-tokens/core/typography.json",
          isSource: true,
          original: {
            value: "Mulish, sans-serif",
            key: "{typography.font.family.primary}",
          },
          name: "TypographyFontFamilyPrimary",
          attributes: {
            category: "typography",
            type: "font",
            item: "family",
            subitem: "primary",
          },
          path: ["typography", "font", "family", "primary"],
        },
        heading: {
          key: "{typography.font.family.heading}",
          value: "Mulish, sans-serif",
          filePath: "design-tokens/core/typography.json",
          isSource: true,
          original: {
            value: "Mulish, sans-serif",
            key: "{typography.font.family.heading}",
          },
          name: "TypographyFontFamilyHeading",
          attributes: {
            category: "typography",
            type: "font",
            item: "family",
            subitem: "heading",
          },
          path: ["typography", "font", "family", "heading"],
        },
        mono: {
          key: "{typography.font.family.mono}",
          value: "Fira Code, monospace",
          filePath: "design-tokens/core/typography.json",
          isSource: true,
          original: {
            value: "Fira Code, monospace",
            key: "{typography.font.family.mono}",
          },
          name: "TypographyFontFamilyMono",
          attributes: {
            category: "typography",
            type: "font",
            item: "family",
            subitem: "mono",
          },
          path: ["typography", "font", "family", "mono"],
        },
      },
    },
    size: {
      xs: {
        key: "{typography.size.xs}",
        value: "12",
        filePath: "design-tokens/core/typography.json",
        isSource: true,
        original: {
          value: "12",
          key: "{typography.size.xs}",
        },
        name: "TypographySizeXs",
        attributes: {
          category: "typography",
          type: "size",
          item: "xs",
        },
        path: ["typography", "size", "xs"],
      },
      sm: {
        key: "{typography.size.sm}",
        value: "14",
        filePath: "design-tokens/core/typography.json",
        isSource: true,
        original: {
          value: "14",
          key: "{typography.size.sm}",
        },
        name: "TypographySizeSm",
        attributes: {
          category: "typography",
          type: "size",
          item: "sm",
        },
        path: ["typography", "size", "sm"],
      },
      base: {
        key: "{typography.size.base}",
        value: "16",
        filePath: "design-tokens/core/typography.json",
        isSource: true,
        original: {
          value: "16",
          key: "{typography.size.base}",
        },
        name: "TypographySizeBase",
        attributes: {
          category: "typography",
          type: "size",
          item: "base",
        },
        path: ["typography", "size", "base"],
      },
      lg: {
        key: "{typography.size.lg}",
        value: "18",
        filePath: "design-tokens/core/typography.json",
        isSource: true,
        original: {
          value: "18",
          key: "{typography.size.lg}",
        },
        name: "TypographySizeLg",
        attributes: {
          category: "typography",
          type: "size",
          item: "lg",
        },
        path: ["typography", "size", "lg"],
      },
      xl: {
        key: "{typography.size.xl}",
        value: "20",
        filePath: "design-tokens/core/typography.json",
        isSource: true,
        original: {
          value: "20",
          key: "{typography.size.xl}",
        },
        name: "TypographySizeXl",
        attributes: {
          category: "typography",
          type: "size",
          item: "xl",
        },
        path: ["typography", "size", "xl"],
      },
      "2xl": {
        key: "{typography.size.2xl}",
        value: "24",
        filePath: "design-tokens/core/typography.json",
        isSource: true,
        original: {
          value: "24",
          key: "{typography.size.2xl}",
        },
        name: "TypographySize2xl",
        attributes: {
          category: "typography",
          type: "size",
          item: "2xl",
        },
        path: ["typography", "size", "2xl"],
      },
      "3xl": {
        key: "{typography.size.3xl}",
        value: "30",
        filePath: "design-tokens/core/typography.json",
        isSource: true,
        original: {
          value: "30",
          key: "{typography.size.3xl}",
        },
        name: "TypographySize3xl",
        attributes: {
          category: "typography",
          type: "size",
          item: "3xl",
        },
        path: ["typography", "size", "3xl"],
      },
      "4xl": {
        key: "{typography.size.4xl}",
        value: "36",
        filePath: "design-tokens/core/typography.json",
        isSource: true,
        original: {
          value: "36",
          key: "{typography.size.4xl}",
        },
        name: "TypographySize4xl",
        attributes: {
          category: "typography",
          type: "size",
          item: "4xl",
        },
        path: ["typography", "size", "4xl"],
      },
      "5xl": {
        key: "{typography.size.5xl}",
        value: "48",
        filePath: "design-tokens/core/typography.json",
        isSource: true,
        original: {
          value: "48",
          key: "{typography.size.5xl}",
        },
        name: "TypographySize5xl",
        attributes: {
          category: "typography",
          type: "size",
          item: "5xl",
        },
        path: ["typography", "size", "5xl"],
      },
      "6xl": {
        key: "{typography.size.6xl}",
        value: "60",
        filePath: "design-tokens/core/typography.json",
        isSource: true,
        original: {
          value: "60",
          key: "{typography.size.6xl}",
        },
        name: "TypographySize6xl",
        attributes: {
          category: "typography",
          type: "size",
          item: "6xl",
        },
        path: ["typography", "size", "6xl"],
      },
    },
    weight: {
      light: {
        key: "{typography.weight.light}",
        value: "300",
        filePath: "design-tokens/core/typography.json",
        isSource: true,
        original: {
          value: "300",
          key: "{typography.weight.light}",
        },
        name: "TypographyWeightLight",
        attributes: {
          category: "typography",
          type: "weight",
          item: "light",
        },
        path: ["typography", "weight", "light"],
      },
      normal: {
        key: "{typography.weight.normal}",
        value: "400",
        filePath: "design-tokens/core/typography.json",
        isSource: true,
        original: {
          value: "400",
          key: "{typography.weight.normal}",
        },
        name: "TypographyWeightNormal",
        attributes: {
          category: "typography",
          type: "weight",
          item: "normal",
        },
        path: ["typography", "weight", "normal"],
      },
      medium: {
        key: "{typography.weight.medium}",
        value: "500",
        filePath: "design-tokens/core/typography.json",
        isSource: true,
        original: {
          value: "500",
          key: "{typography.weight.medium}",
        },
        name: "TypographyWeightMedium",
        attributes: {
          category: "typography",
          type: "weight",
          item: "medium",
        },
        path: ["typography", "weight", "medium"],
      },
      semibold: {
        key: "{typography.weight.semibold}",
        value: "600",
        filePath: "design-tokens/core/typography.json",
        isSource: true,
        original: {
          value: "600",
          key: "{typography.weight.semibold}",
        },
        name: "TypographyWeightSemibold",
        attributes: {
          category: "typography",
          type: "weight",
          item: "semibold",
        },
        path: ["typography", "weight", "semibold"],
      },
      bold: {
        key: "{typography.weight.bold}",
        value: "700",
        filePath: "design-tokens/core/typography.json",
        isSource: true,
        original: {
          value: "700",
          key: "{typography.weight.bold}",
        },
        name: "TypographyWeightBold",
        attributes: {
          category: "typography",
          type: "weight",
          item: "bold",
        },
        path: ["typography", "weight", "bold"],
      },
      extrabold: {
        key: "{typography.weight.extrabold}",
        value: "800",
        filePath: "design-tokens/core/typography.json",
        isSource: true,
        original: {
          value: "800",
          key: "{typography.weight.extrabold}",
        },
        name: "TypographyWeightExtrabold",
        attributes: {
          category: "typography",
          type: "weight",
          item: "extrabold",
        },
        path: ["typography", "weight", "extrabold"],
      },
    },
  },
  terra: {
    green: {
      light: {
        key: "{terra.green.light}",
        value: "#86efac",
        filePath: "design-tokens/terra-nova/brand.json",
        isSource: true,
        original: {
          value: "#86efac",
          key: "{terra.green.light}",
        },
        name: "TerraGreenLight",
        attributes: {
          category: "terra",
          type: "green",
          item: "light",
        },
        path: ["terra", "green", "light"],
      },
      primary: {
        key: "{terra.green.primary}",
        value: "#22c55e",
        filePath: "design-tokens/terra-nova/brand.json",
        isSource: true,
        original: {
          value: "#22c55e",
          key: "{terra.green.primary}",
        },
        name: "TerraGreenPrimary",
        attributes: {
          category: "terra",
          type: "green",
          item: "primary",
        },
        path: ["terra", "green", "primary"],
      },
      dark: {
        key: "{terra.green.dark}",
        value: "#15803d",
        filePath: "design-tokens/terra-nova/brand.json",
        isSource: true,
        original: {
          value: "#15803d",
          key: "{terra.green.dark}",
        },
        name: "TerraGreenDark",
        attributes: {
          category: "terra",
          type: "green",
          item: "dark",
        },
        path: ["terra", "green", "dark"],
      },
      forest: {
        key: "{terra.green.forest}",
        value: "#14532d",
        filePath: "design-tokens/terra-nova/brand.json",
        isSource: true,
        original: {
          value: "#14532d",
          key: "{terra.green.forest}",
        },
        name: "TerraGreenForest",
        attributes: {
          category: "terra",
          type: "green",
          item: "forest",
        },
        path: ["terra", "green", "forest"],
      },
    },
    earth: {
      light: {
        key: "{terra.earth.light}",
        value: "#fbbf24",
        filePath: "design-tokens/terra-nova/brand.json",
        isSource: true,
        original: {
          value: "#fbbf24",
          key: "{terra.earth.light}",
        },
        name: "TerraEarthLight",
        attributes: {
          category: "terra",
          type: "earth",
          item: "light",
        },
        path: ["terra", "earth", "light"],
      },
      primary: {
        key: "{terra.earth.primary}",
        value: "#a16207",
        filePath: "design-tokens/terra-nova/brand.json",
        isSource: true,
        original: {
          value: "#a16207",
          key: "{terra.earth.primary}",
        },
        name: "TerraEarthPrimary",
        attributes: {
          category: "terra",
          type: "earth",
          item: "primary",
        },
        path: ["terra", "earth", "primary"],
      },
      dark: {
        key: "{terra.earth.dark}",
        value: "#78350f",
        filePath: "design-tokens/terra-nova/brand.json",
        isSource: true,
        original: {
          value: "#78350f",
          key: "{terra.earth.dark}",
        },
        name: "TerraEarthDark",
        attributes: {
          category: "terra",
          type: "earth",
          item: "dark",
        },
        path: ["terra", "earth", "dark"],
      },
    },
    sky: {
      light: {
        key: "{terra.sky.light}",
        value: "#7dd3fc",
        filePath: "design-tokens/terra-nova/brand.json",
        isSource: true,
        original: {
          value: "#7dd3fc",
          key: "{terra.sky.light}",
        },
        name: "TerraSkyLight",
        attributes: {
          category: "terra",
          type: "sky",
          item: "light",
        },
        path: ["terra", "sky", "light"],
      },
      primary: {
        key: "{terra.sky.primary}",
        value: "#0ea5e9",
        filePath: "design-tokens/terra-nova/brand.json",
        isSource: true,
        original: {
          value: "#0ea5e9",
          key: "{terra.sky.primary}",
        },
        name: "TerraSkyPrimary",
        attributes: {
          category: "terra",
          type: "sky",
          item: "primary",
        },
        path: ["terra", "sky", "primary"],
      },
      dark: {
        key: "{terra.sky.dark}",
        value: "#0c4a6e",
        filePath: "design-tokens/terra-nova/brand.json",
        isSource: true,
        original: {
          value: "#0c4a6e",
          key: "{terra.sky.dark}",
        },
        name: "TerraSkyDark",
        attributes: {
          category: "terra",
          type: "sky",
          item: "dark",
        },
        path: ["terra", "sky", "dark"],
      },
    },
    flower: {
      pink: {
        key: "{terra.flower.pink}",
        value: "#f472b6",
        filePath: "design-tokens/terra-nova/brand.json",
        isSource: true,
        original: {
          value: "#f472b6",
          key: "{terra.flower.pink}",
        },
        name: "TerraFlowerPink",
        attributes: {
          category: "terra",
          type: "flower",
          item: "pink",
        },
        path: ["terra", "flower", "pink"],
      },
      purple: {
        key: "{terra.flower.purple}",
        value: "#a855f7",
        filePath: "design-tokens/terra-nova/brand.json",
        isSource: true,
        original: {
          value: "#a855f7",
          key: "{terra.flower.purple}",
        },
        name: "TerraFlowerPurple",
        attributes: {
          category: "terra",
          type: "flower",
          item: "purple",
        },
        path: ["terra", "flower", "purple"],
      },
      orange: {
        key: "{terra.flower.orange}",
        value: "#fb923c",
        filePath: "design-tokens/terra-nova/brand.json",
        isSource: true,
        original: {
          value: "#fb923c",
          key: "{terra.flower.orange}",
        },
        name: "TerraFlowerOrange",
        attributes: {
          category: "terra",
          type: "flower",
          item: "orange",
        },
        path: ["terra", "flower", "orange"],
      },
    },
  },
};
